# === Site basics ===
title: "Tianle Niu"
name: "Tianle Niu"
description: "AI for Computational Pharmacology"
url: "https://jeffreynt1.github.io"
baseurl: ""   # 改仓库名为 jeffreynt1.github.io 时，把这里改成 ""

# === Theme ===
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# === Build ===
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
permalink: /:title/

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# === Author/sidebar ===
author:
  name: "Tianle Niu"
  avatar: "/assets/images/avatar.png"
  bio: "Master's student @ ZJU. AI-driven drug discovery & computational pharmacology."
  location: "Hangzhou, China"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:niutianle@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeffreynt1"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "#"

# === Defaults ===
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

collections:
  posts:
    output: true
